image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

nuget:
  account_feed: true
  project_feed: true

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
build:
  project: Tracer.sln
  verbosity: minimal

after_build:
  - cmd: nuget pack .\Tracer.NLog\NuGet\Tracer.NLog.Fody.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Tracer.NLog.Fody.%GitVersion_NuGetVersion%.nupkg"
